MRSArchisWFApp/Models/CaseService/document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Xml.Serialization;
using MRSArchis.OpenText.CS.DataAnnotations;

namespace MRSArchisWFApp.MRSArchisWS
{
  [CSCategoryName("Documenttype", "CAT_MRS_DocType")]
  public partial class document : Helpers.ICachedData
  {
    #region private members
    private string _mainType;
    private string _subType;
    #endregion

    #region interface implementation
    [XmlIgnore()]
    public string cacheId { get; set; }

    [XmlIgnore()]
    public string sessionId { get; set; }

    [XmlIgnore()]
    public string workItemId { get; set; }

    [XmlIgnore()]
    public string currentStep { get; set; }

    [XmlIgnore()]
    public bool isDirty { get; set; }

    [XmlIgnore()]
    public bool isNew { get; set; }

    [XmlIgnore()]
    public bool isDeleted { get; set; }

    [XmlIgnore()]
    public bool isReadOnly { get; set; }
    #endregion

    #region Extra properties
    [XmlIgnore()]
    [DisplayName("Hoofdtype")]
    [CSFieldName("Hoofdtype")]
    public string mainType
    {
      get { return _mainType; }
      set
      {
        if (value != _mainType)
        {
          _mainType = value;
          isDirty = true;
        }
      }
    }

    [XmlIgnore()]
    [DisplayName("Subtype")]
    [CSFieldName("Subtype")]
    public string subType
    {
      get { return _subType; }
      set
      {
        if (value != _subType)
        {
          _subType = value;
          isDirty = true;
        }
      }
    }
    #endregion
  }
}

MRSArchisWFApp/Models/CaseService/documenttype.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace MRSArchisWFApp.MRSArchisWS
{
  public partial class documenttype : Helpers.ICachedData
  {
    #region interface implementation
    [XmlIgnore()]
    public string cacheId { get; set; }

    [XmlIgnore()]
    public string sessionId { get; set; }

    [XmlIgnore()]
    public string workItemId { get; set; }

    [XmlIgnore()]
    public string currentStep { get; set; }

    [XmlIgnore()]
    public bool isDirty { get; set; }

    [XmlIgnore()]
    public bool isNew { get; set; }

    [XmlIgnore()]
    public bool isDeleted { get; set; }

    [XmlIgnore()]
    public bool isReadOnly { get; set; }
    #endregion
  }
}

MRSArchisWFApp/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MRSArchisWFApp.Helpers;
using MRSArchisWFApp.Helpers.MRSArchis;
using MRSArchisWFApp.MRSArchisWS;

namespace MRSArchisWFApp.Controllers
{
    public class DocumentController : Controller
    {
      public ActionResult Index()
      {
        try
        {
          // Update the case data in case it is out of sync
          var cdata = Helpers.EPS.CaseDataHelper.CaseData;
          cdata.numAttachments = DocumentHelper.Documents.Count;
          return View(DocumentHelper.Documents.OrderBy(d => d.titel.ToUpper()));
        }
        catch (Exception ex)
        {
          ViewBag.message = ex.Message;
        }
        return View("Error");
      }

      public ActionResult Edit(string id)
      {
        try
        {
          return View(DocumentHelper.GetCacheObject(id));
        }
        catch (Exception ex)
        {
          ViewBag.message = ex.Message;
        }
        return View("Error");
      }

      [HttpPost]
      public ActionResult Edit(string id, int documenttypeId, FormCollection collection)
      {
        try
        {
          document doc = DocumentHelper.GetCacheObject(id);
          Helpers.UtilityHelper.FormatCollectionForModel(collection);
          TryUpdateModel(doc, collection);
          TryUpdateModel(doc);
          // Set the subtype field 
          doc.subType = DocumentTypesHelper.GetDocumentSubTypeFor(documenttypeId);
          return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
          ViewBag.message = ex.Message;
        }
        return View("Error");
      }

      public ActionResult Delete(string id)
      {
        try
        {
          return View(DocumentHelper.GetCacheObject(id));
        }
        catch (Exception ex)
        {
          ViewBag.message = ex.Message;
        }
        return View("Error");
      }

      [HttpPost]
      public ActionResult Delete(string id, FormCollection collection)
      {
        try
        {
          DocumentHelper.Delete(id);

          // Update databse and case data
          var cdata = Helpers.EPS.CaseDataHelper.CaseData;
          cdata.numAttachments = DocumentHelper.Documents.Count;
          return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
          ViewBag.message = ex.Message;
        }
        return View("Error");
      }

      public ActionResult GetDocumentSubTypes(string mainType)
      {
        return Json(DocumentTypesHelper.GetDocumentSubTypesFor(mainType), JsonRequestBehavior.AllowGet);
      }
    }
}

MRSArchisWFApp/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MRSArchisWFApp.Helpers;

namespace MRSArchisWFApp.Controllers
{
    public class FileUploadController : Controller
    {
      public ActionResult Index(string multipleUploader)
      {
        try
        {
          using (CuteWebUI.MvcUploader uploader = new CuteWebUI.MvcUploader(System.Web.HttpContext.Current))
          {
            uploader.UploadUrl = Response.ApplyAppPathModifier("~/UploadHandler.ashx");
            //the data of the uploader will render as <input type='hidden' name='myuploader'> 
            uploader.Name = "multipleUploader";
            uploader.AllowedFileExtensions = UtilityHelper.AllowedUploadExtensions;
            uploader.MaxSizeKB = UtilityHelper.UploadMaxSizeKB;
            uploader.InsertText = "Selecteer bestanden om te uploaden";
            uploader.FileTypeNotSupportMsg = "Dit bestandtype is niet toegestaan. Toegestane extensies zijn: " + uploader.AllowedFileExtensions;
            //allow select multiple files
            uploader.MultipleFilesUpload = true;
            //tell uploader attach a button
            uploader.InsertButtonID = "uploadbutton";
            //prepair html code for the view
            ViewData["uploaderhtml"] = uploader.Render();
            //if it's HTTP POST:
            if (!string.IsNullOrEmpty(multipleUploader))
            {
              List<string> processedfiles = new List<string>();
              List<string> skippedExtensions = new List<string>();
              //for multiple files , the value is string : guid/guid/guid 
              foreach (string strguid in multipleUploader.Split('/'))
              {
                Guid fileguid = new Guid(strguid);
                CuteWebUI.MvcUploadFile file = uploader.GetUploadedFile(fileguid);
                if (file != null)
                {
                  string extension = Path.GetExtension(file.FileName).ToLower();
                  if (uploader.AllowedFileExtensions.Split(',').FirstOrDefault(s => s == extension.Substring(1)) != null)
                  {
                    // For testing
                    //string path = Server.MapPath("~/UploadedFiles/");
                    //file_upload.SaveAs(path + file.FileName);
                    string nodeId = SessionHandler.CSHelperObject.Upload(
                      SessionHandler.CSHelperObject.GetCaseFolder(SessionHandler.CaseNumber), file.OpenStream(), file.FileName);
                    DocumentHelper.AddFile(file, int.Parse(nodeId));
                    processedfiles.Add(file.FileName);
                  }
                  else if (!skippedExtensions.Exists(e => string.Compare(e, extension, true) == 0))
                    skippedExtensions.Add(Path.GetExtension(file.FileName));
                }
              }
              if (processedfiles.Count > 0)
              {
                // TODO: Save immediately to db avoid inconsistency if user doesn't save data
                
                var cdata = Helpers.EPS.CaseDataHelper.CaseData;
                cdata.numAttachments = DocumentHelper.Documents.Count;
                ViewBag.message = string.Join(",", processedfiles.ToArray()) + (processedfiles.Count == 1 ? " is" : " zijn") + " geüpload. ";
              }
              ViewBag.message += skippedExtensions.Count > 1 ? string.Join(",", skippedExtensions.ToArray()) + " bestanden kunnen niet worden geüpload." : string.Empty;
            }
          }
          return View();
        }
        catch (Exception ex)
        {
          ViewBag.message = ex.Message;
        }

        return View("Error");
      }

      public ActionResult ClassicUpload(string uploadresult)
      {
        ViewBag.message = uploadresult;
        return View();
      }

      [HttpPost]
      public ActionResult ClassicUpload(HttpPostedFileBase file_upload)
      {
        try
        {
          string AllowedFileExtensions = UtilityHelper.AllowedUploadExtensions;
          var fileName = Path.GetFileName(file_upload.FileName);
          string extension = Path.GetExtension(fileName).ToLower();
          if (AllowedFileExtensions.Split(',').FirstOrDefault(s => s.IndexOf(extension) != -1) != null)
          {
            // For testing
            //string path = Server.MapPath("~/UploadedFiles/");
            //file_upload.SaveAs(path + fileName);
            string nodeId = SessionHandler.CSHelperObject.Upload(
              SessionHandler.CSHelperObject.GetCaseFolder(SessionHandler.CaseNumber), file_upload.InputStream, fileName);
            DocumentHelper.AddFile(file_upload, int.Parse(nodeId));
            // TO DO: Save immediately to db avoid inconsistency if user doesn't save data

            var cdata = Helpers.EPS.CaseDataHelper.CaseData;
            cdata.numAttachments = DocumentHelper.Documents.Count;
            return RedirectToAction("ClassicUpload", new { uploadresult = Url.Encode(fileName) + " is geüpload." });
          }
          return RedirectToAction("ClassicUpload", new { uploadresult = Url.Encode(extension.Substring(1).ToUpper()) + " bestanden kunnen niet worden geüpload." });
        }
        catch (Exception ex)
        {
          ViewBag.message = ex.Message;
        }

        return View("Error");
      }
    }
}

MRSArchisWFApp/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MRSArchisWFApp.Helpers;

namespace MRSArchisWFApp.Controllers
{
  public class SearchController : Controller
  {
    public ActionResult Index(string mainType, string documentTypeId, string searchTerm, string returnUrl)
    {
      return View();
    }

    public ActionResult Results(string mainType, string documentTypeId, string searchTerm, string returnUrl)
    {
      try
      {
        ViewBag.searchTerm = searchTerm;
        ViewBag.returnUrl = returnUrl;
        return View(SessionHandler.CSHelperObject.SearchCaseForDocumentType(
          Helpers.MRSArchis.CaseHelper.GetBaseCaseNumber(SessionHandler.CaseNumber), mainType, documentTypeId, searchTerm));
      }
      catch (Exception ex)
      {
        ViewBag.message = ex.Message;
      }
      return View("Error");
    }
  }
}

MRSArchisWFApp/Views/Document/Delete.cshtml
@using MRSArchis.OpenText;

@model MRSArchisWFApp.MRSArchisWS.document
@{
    ViewBag.Title = "Documenten";
}

<h2>Document verwijderen</h2>
<fieldset>
    <legend>@Html.DisplayFor(model => model.titel)</legend>
    <div class="display-label">
        @Html.LabelFor(model => model.bestandsnaam)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.bestandsnaam)
    </div>
    <div class="display-label">
        @Html.LabelFor(model => model.creatiedatum)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.creatiedatum)
    </div>
    <div class="display-label">
        @Html.LabelFor(model => model.mainType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.mainType)
    </div>
    <div class="display-label">
        @Html.DisplayFor(model => model.subType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.subType)
    </div>
    <div class="display-label">
        @Html.LabelFor(model => model.link)
    </div>
    <div class="display-field">
        @if (!string.IsNullOrEmpty(Model.link))
        {
            <a href="@Url.Content(CSHelper.CSUrl + "?func=ll&objAction=download&objId=" + @Html.DisplayFor(model => model.link)))" 
                target="_blank" title="Klik om te downloaden">@Html.DisplayFor(model => Model.bestandsnaam)</a>
        }
        else
        {
            <text>Bestand niet aanwezig</text>
        }
    </div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Verwijder" />
        |
        @Html.ActionLink("Terug naar de lijst", "Index")
    </p>
}

MRSArchisWFApp/Views/Document/Edit.cshtml
@using MRSArchisWFApp.Models;
@using MRSArchisWFApp.Helpers.MRSArchis;
@using MRSArchis.OpenText;

@model MRSArchisWFApp.MRSArchisWS.document
@{
    ViewBag.Title = "Documenten";
}
<h2>Bewerk</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Date received
        $("#ontvangstdatum").datepicker({ dateFormat: "dd-mm-yy", defaultDate: 0, maxDate: 0 });

        // Set the dropdown lists for document type selection
        $("#mainType").change(function () {
            $.getJSON('@Url.Content("~/Document/GetDocumentSubTypes?mainType=")' + $("#mainType").val(), function (data) {
                $('#documenttypeId').empty();
                $.each(data, function (key, val) {
                    $('#documenttypeId').append(
                        $('<option value="' + val.Value + '">', { key: val }).text(val.Text));
                });
            });
        });
    });
</script>
@{ Html.RenderPartial("_EditHelpers"); }
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Documentgegevens bewerken</legend>
        @Html.HiddenFor(model => model.cacheId)
        @Html.HiddenFor(model => model.isDirty)
        <div class="display-label">
            @Html.LabelFor(model => model.titel)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.titel)
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.bestandsnaam)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.bestandsnaam)
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.bestandsgrootte)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.bestandsgrootte)
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.creatiedatum)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.creatiedatum)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.auteur)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.auteur)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.beschrijving)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.beschrijving, 3, 40, null)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ontvangstdatum)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ontvangstdatum)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.mainType)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.mainType, new SelectList(DocumentTypesHelper.GetDocumentMainTypes))
            @Html.ValidationMessageFor(model => model.mainType)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.documenttypeId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.documenttypeId, DocumentTypesHelper.GetDocumentSubTypesFor(Model.mainType))
            @Html.ValidationMessageFor(model => model.documenttypeId)
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.link)
        </div>
        <div class="editor-field">
            <!-- Note either filename or title can be used to identify the form xml, but filename is more safe -->
            @if (!string.IsNullOrEmpty(Model.link))
            {
                <a href="@Url.Content(CSHelper.CSUrl + "?func=ll&objAction=download&objId=" + @Html.DisplayFor(model => model.link)))" 
                target="_blank" title="Klik om te downloaden">@Html.DisplayFor(model => model.bestandsnaam)</a>
            }
            else
            {
                @Html.DisplayFor(model => model.bestandsnaam)
            }
        </div>
        <p>
            <input type="submit" value="Bevestig" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Terug naar de lijst", "Index")
</div>

MRSArchisWFApp/Views/Document/Index.cshtml
@using MRSArchis.OpenText;
@using MRSArchisWFApp.Helpers.EPS;
@using MRSArchisWFApp.MRSArchisWS;

@model IEnumerable<document>
@{
    ViewBag.Title = "Documenten";
}
<h1>Zaakdocumenten</h1>

@if (!string.IsNullOrEmpty(CaseDataHelper.CaseData.caseNumber))
{
    <p>
        @Html.ActionLink("Document uploaden", "Index", "FileUpload")
        |
        @Html.ActionLink("Document zoeken", "Index", "Search")
    </p>
}

<table class="realTable">
    <tr>
        <th>Bestand
        </th>
        <th>Creatiedatum
        </th>
        <th>Hoofdtype
        </th>
        <th>Subtype
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (!string.IsNullOrEmpty(item.link))
                {
                    <a href="@Url.Content(CSHelper.CSUrl + "?func=ll&objAction=download&objId=" + @Html.DisplayFor(modelItem => item.link)))" 
                            target="_blank" title="Klik om @item.bestandsnaam te downloaden">@Html.DisplayFor(modelItem => item.titel)@System.IO.Path.GetExtension(item.bestandsnaam)</a> 
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.titel)@System.IO.Path.GetExtension(item.bestandsnaam)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.creatiedatum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mainType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.subType)
            </td>
            <td>
                @Html.ActionLink("Bewerk", "Edit", new { id = item.cacheId }) |
                @Html.ActionLink("Verwijder", "Delete", new { id = item.cacheId })
            </td>
        </tr>
    }
</table>