MRSArchisWFApp/Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MRSArchisWFApp.Models.EPS;
using MRSArchisWFApp.Models.CaseService;
using MRSArchisWFApp.Helpers;
using MRSArchisWFApp.Helpers.EPS;
using MRSArchisWFApp.Helpers.MRSArchis;

namespace MRSArchisWFApp.Controllers
{
  public class CaseController : Controller
  {
    #region log4net
    // Create a logger for this class
    private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
    #endregion

    /// <summary>
    /// General case summarry overview. This view is for diaply only and
    /// does not have form element.
    /// </summary>
    /// <returns>The case summary view ("Zaak")</returns>
    public ActionResult Overview()
    {
      try
      {
        CaseData cdata = CaseDataHelper.CaseData;
        return View(cdata);
      }
      catch (Exception ex)
      {
        ViewBag.message = ex.Message;
      }
      return View("Error");
    }

    /// <summary>
    /// Prepare the view for creating a new case with registration and
    /// receipt data initialized.
    /// </summary>
    /// <returns>View for creating a new case ("Nieuwe zaak")</returns>
    public ActionResult CreateNewCase()
    {
      try
      {
        CaseData cdata = CaseDataHelper.CaseData;

        // Initalize null registration and receipt date to today
        if (!cdata.registrationDate.HasValue)
          cdata.registrationDate = DateTime.Now;
        if (!cdata.receiptDate.HasValue)
          cdata.receiptDate = DateTime.Now;

        // Initialize null scan request and receipt note to true
        if (!cdata.receiptNote.HasValue)
          cdata.receiptNote = false;
        if (!cdata.scanRequest.HasValue)
          cdata.scanRequest = false;

        if (!string.IsNullOrEmpty(cdata.caseNumber))
        {
          cdata.caseReference = CaseHelper.MainCaseNumber;
        }
        return View(cdata);
      }
      catch (Exception ex)
      {
        ViewBag.message = ex.Message;
      }

      return View("Error");
    }
    /// <summary>
    /// Create a case number and folder
    /// </summary>
    /// <returns>JSON with case number ("zaaknummer") an case year id (subregelingAanvraagJaarId)</returns>
    public ActionResult GetCaseNumber(
      string caseReference, 
      string caseTypeName, 
      string roleTypeName, 
      string statusTypeName, 
      string registrationDate, 
      string receiptDate)
    {
      try
      {
        CaseData cdata = CaseDataHelper.CaseData;

        cdata.roleTypeName = roleTypeName;
        cdata.roleTypeId = CaseHelper.GetRoleTypeId(roleTypeName);
        cdata.caseTypeName = caseTypeName;
        cdata.caseTypeId = CaseHelper.GetCaseTypeId(caseTypeName, cdata.roleTypeId);
        cdata.statusTypeName = statusTypeName;
        cdata.statusTypeId = CaseHelper.GetStatusTypeId(cdata.statusTypeName);
        cdata.caseReference = caseReference;

        cdata.registrationDate = MRSArchis.OpenText.Helpers.UtilityHelper.StringToNullableDate(registrationDate);
        cdata.receiptDate = MRSArchis.OpenText.Helpers.UtilityHelper.StringToNullableDate(receiptDate);
        if (!cdata.registrationDate.HasValue || !cdata.receiptDate.HasValue)
          throw new Exception("Ongeldige registratie- of ontvangstdatum");

        //cdata.caseNumber = new Random().Next(10000, 99999).ToString() + new Random().Next(10000, 99999).ToString();
        if (string.IsNullOrEmpty(cdata.caseReference))
        {
          cdata.caseNumber = CaseHelper.CreateCase(
            2,                                    /* 0-9, determines the first digit of the generated case number */
            cdata.registrationDate,               /* Date case is registered */
            cdata.receiptDate,                    /* Date case was received */
            cdata.roleTypeId,                     /* The id of the role name */
            cdata.caseTypeId.GetValueOrDefault(), /* The id of the case type */
            cdata.statusTypeId,                   /* The id of the case status */
            caseReference                         /* The reference case number for a subsequent case number */
            );
          SessionHandler.CSHelperObject.CreateCaseFolder(cdata.caseNumber);
        }
        /*
        else
        {
          if (string.IsNullOrEmpty(cdata.caseReference))
            throw new Exception("Gerelateerd zaaknummer is verplicht voor wijziging, melding of vaststelling");

          try
          {
            CaseDetail caseDetail = Helpers.SACE.CaseHelper.GetCaseDetail(cdata.caseReference);
            CaseHelper.SetCaseYearName(caseDetail.caseYearNameId.GetValueOrDefault().ToString(), ref cdata);
          }
          catch
          {
            throw new Exception("Het gerelateerde zaaknummer bestaat niet");
          }
          cdata.caseNumber = Helpers.SACE.CaseHelper.GetSequenceNumber(cdata.caseReference, (CaseTypes)Enum.Parse(typeof(CaseTypes), cdata.caseType));
          CSHelper.CreateCaseFolder(cdata.caseNumber);
        }
       */
        SessionHandler.CaseNumber = cdata.caseNumber;

        // Save it to process and CS to fix values
        CaseDataHelper.SaveToDB();

        return new JsonResult
        {
          JsonRequestBehavior = JsonRequestBehavior.AllowGet,
          Data = new { error = false, caseNumber = cdata.caseNumber }
        };
      }
      catch (Exception ex)
      {
        return new JsonResult
        {
          JsonRequestBehavior = JsonRequestBehavior.AllowGet,
          Data = new { error = true, message = ex.Message }
        };
      }
    }

    public ActionResult GetCaseRoleList(long? caseTypeId)
    {
      return Json(CaseHelper.GetCaseRoleTypes(caseTypeId), JsonRequestBehavior.AllowGet);
    }

    public ActionResult IntakeMRSCase()
    {
      try
      {
        CaseData cdata = CaseDataHelper.CaseData;
        return View(cdata);
      }
      catch (Exception ex)
      {
        ViewBag.message = ex.Message;
      }
      return View("Error");
    }

    public ActionResult IntakeAddMonument()
    {
      try
      {
        CaseData cdata = CaseDataHelper.CaseData;
        return View(cdata);
      }
      catch (Exception ex)
      {
        ViewBag.message = ex.Message;
      }
      return View("Error");
    }

    public ActionResult IntakeChangeMonument()
    {
      try
      {
        CaseData cdata = CaseDataHelper.CaseData;
        return View(cdata);
      }
      catch (Exception ex)
      {
        ViewBag.message = ex.Message;
      }
      return View("Error");
    }

    public ActionResult IntakeDeleteMonument()
    {
      try
      {
        CaseData cdata = CaseDataHelper.CaseData;
        return View(cdata);
      }
      catch (Exception ex)
      {
        ViewBag.message = ex.Message;
      }
      return View("Error");
    }
  }
}

MRSArchisWFApp/Controllers/DicoController.cs
using MRSArchisWFApp.CHOService;
using MRSArchisWFApp.Helpers;
using MRSArchisWFApp.Helpers.CHO;
using MRSArchisWFApp.Helpers.EPS;
using MRSArchisWFApp.Helpers.MRSArchis;
using MRSArchisWFApp.MRSArchisWS;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MRSArchisWFApp.Controllers
{
    public class DicoController : Controller
    {
        public ActionResult ShowWGPViewer()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View(MonumentHelper.Monuments);
        }

        public ActionResult Edit(string uploadresult, string cacheId)
        {
            try
            {
                ViewBag.message = uploadresult;

                return View(MonumentHelper.GetCacheObject(cacheId));
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View("Error");
        }
        
        [HttpPost]
        // When using rijksmonument as a parameter geometrie and locationDescription doesn't get filled, so used FormCollection
        public ActionResult Edit(string uploadresult, string cacheId, FormCollection fc)        
        {
            try
            {
                string beschrijving = fc.GetValue("beschrijving").AttemptedValue;
                int herkomstId = Convert.ToInt32(fc.GetValue("geometrie.herkomstId").AttemptedValue);
                int mateOvernameId = Convert.ToInt32(fc.GetValue("geometrie.mateOvernameId").AttemptedValue);
                int kwaliteitGeometrieId = Convert.ToInt32(fc.GetValue("geometrie.kwaliteitGeometrieId").AttemptedValue);

                var monument = MonumentHelper.GetCacheObject(cacheId);
                
                monument.geometrie.herkomstId = herkomstId;
                monument.geometrie.herkomstIdSpecified = true;
                monument.geometrie.mateOvernameId = mateOvernameId;
                monument.geometrie.mateOvernameIdSpecified = true;
                monument.geometrie.kwaliteitGeometrieId = kwaliteitGeometrieId;
                monument.geometrie.kwaliteitGeometrieIdSpecified = true;
                monument.geometrie.isDirty = true;

                var document = DocumentHelper.Documents.First(d => d.id == monument.geometrie.documentId);
                document.beschrijving = beschrijving;
                document.isDirty = true;

                return RedirectToAction("Edit", new { uploadresult = "", cacheId = cacheId });
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View("Error");
        }

        public ActionResult Delete(string cacheId)
        {
            try
            {
                return View(MonumentHelper.GetCacheObject(cacheId));
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View("Error");            
        }

        [HttpPost]
        public ActionResult Delete(string cacheId, FormCollection formCollection)
        {
            try
            {
                MonumentHelper.Delete(cacheId);
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return RedirectToAction("Index");
        }

        public ActionResult Upload(string cacheId)
        {
            try
            {
                return View(MonumentHelper.GetCacheObject(cacheId));
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View("Error");            
        }
        
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file_upload, string cacheId)
        {
            try
            {
                var fileName = Path.GetFileName(file_upload.FileName);
                var fileExtension = Path.GetExtension(fileName).ToLower();
                if (ExtensionAllowed(fileExtension))
                {
                    var docId = UploadToContentServer(file_upload, fileName);
                    UploadToDatabase(file_upload, ref cacheId, docId);                    

                    return RedirectToAction("Edit", new { uploadresult = Url.Encode(fileName) + " is geüpload.", cacheId = cacheId });
                }
                return RedirectToAction("Edit", new { uploadresult = Url.Encode(fileExtension.Substring(1).ToUpper()) + " bestanden kunnen niet worden geüpload.", cacheId = cacheId });
            }
            catch (Exception ex)
            {
                // TODO: Delete
                ViewBag.message = ex.Message;
            }
            return View("Error");
        }

        public HtmlString GetWidget()
        {            
            return new HtmlString("<script src='http://rce.webgispublisher.nl/widget.ashx?map=MRS-Archis_Aanwijzen_Widget10&bbox=230263.7,554362.2,237682.5,561135.9&ovautoopen=false&slider=smallSlider&doPanel=panelNone&width=200&height=300&ovheight=150&ovwidth=150&glgeol=' language='javascript' id='wgpscript'></script><noscript><p>Uw browser ondersteunt geen JavaScript!</p><p>De (niet getoonde) kaart bevat het volgende:</p><p>MRS/Archis kaart t.b.v. proces Aanwijzen monumenten - Behandelen</p></noscript>");
        }

        private bool ExtensionAllowed(string extension)
        {
            string AllowedFileExtensions = UtilityHelper.AllowedUploadExtensions;

            return AllowedFileExtensions.Split(',').FirstOrDefault(s => s.IndexOf(extension) != -1) != null;
        }

        private void UploadToDatabase(HttpPostedFileBase file, ref string cacheId, long docId)
        {
            CHOServiceClient choService = new CHOServiceClient();
            ZaakServiceClient zaakService = new ZaakServiceClient();
                        
            geometrie geometry;
            rijksmonument monument;

            if (!string.IsNullOrEmpty(cacheId))
            {
                monument = MonumentHelper.GetCacheObject(cacheId);
                geometry = monument.geometrie;
            }
            else
            {
                long zaakId = CaseHelper.GetCaseId(CaseDataHelper.CaseData.caseNumber).GetValueOrDefault();
                
                monument = InsertNewRijksmonument(choService, zaakId);
                monument = MonumentHelper.AddToCache(monument);
                cacheId = monument.cacheId;
                
                var choID = monument.choId; // TODO: I think value choID shouldn't be "ref".
                zaakService.insertZaakobject(zaakId, ref choID, monument.choId);

                geometry = new geometrie();
                geometry.choId = monument.choId;
            }            
            
            // Todo: remove convert
            geometry.statusGeometrieId = Convert.ToInt32(StatesGeometryHelper.getStateGeometryId(StatesGeometryHelper.voorbeschermingsDico01));
            geometry.statusGeometrieIdSpecified = true;
            geometry.beginGeldigheid = DateTime.Now;
            geometry.beginGeldigheidSpecified = true;
            geometry.documentId = docId;
            
            geometry.eindGeldigheidSpecified = false;
            geometry.geometrieIdSpecified = false;            
            geometry.herkomstIdSpecified = false;
            geometry.mateOvernameIdSpecified = false;
            geometry.kwaliteitGeometrieIdSpecified = false;
            
            geometry.gmObject = ReadFileContent(file);

            
            geometry.geometrieId = choService.insertOrUpdateGeometrie(SessionHandler.Username, geometry);            
            geometry.geometrieIdSpecified = true;
                        
            // TODO: Als insertGeometrie klapt dan ook monument verwijderen! Maar ook alleen als monument voorheen nog niet bestond!

            monument.geometrie = geometry;
        }

        private rijksmonument InsertNewRijksmonument(CHOServiceClient choService, long zaakId)
        {
            var monument = new rijksmonument();

            monument.aardMonumentIdSpecified = false;
            monument.bebouwdeKomIdSpecified = false;            
            monument.choIdSpecified = false;
            monument.identificatieImkich = "";
            monument.juridischeStatusIdSpecified = false;
            monument.objectbegingeldigheidSpecified = false;
            monument.objecteindgeldigheidSpecified = false;
            monument.rijksmonumentNummerSpecified = false;
            monument.specialisatieType = Convert.ToInt32(SpecializationTypeHelper.getId(SpecializationTypeHelper.monument)); // 2; // TODO: Remove Convert
            monument.vertrouwelijkheidsAanduidingIdSpecified = false;
            monument.zaakId = zaakId;
                        
            monument.choId = choService.insertOrUpdateRijksmonument(SessionHandler.Username, monument);
            monument.choIdSpecified = true;
            
            return monument;
        }

        private string ReadFileContent(HttpPostedFileBase file)
        {
            // Reposition InputStream to start of file.
            file.InputStream.Position = 0;
            
            return new StreamReader(file.InputStream).ReadToEnd();
        }
        
        private long UploadToContentServer(HttpPostedFileBase file_upload, string fileName)
        {
            string nodeId = SessionHandler.CSHelperObject.Upload(
              SessionHandler.CSHelperObject.GetCaseFolder(SessionHandler.CaseNumber), file_upload.InputStream, fileName);
            var doc = DocumentHelper.AddFile(file_upload, int.Parse(nodeId));
                                
            var cdata = Helpers.EPS.CaseDataHelper.CaseData;
            cdata.numAttachments = DocumentHelper.Documents.Count;

            return doc.id;
        }
    }
}

MRSArchisWFApp/Views/Shared/_EditHelpers.cshtml
<!-- Javascript: general field helpers (partial view: _EditHelpers.cshtml) -->
<script type="text/javascript">
    $(document).ready(function () {
        // Set the dirty flag on change
        $("input").change(function () {
            $('#isDirty').val(true);
        });
        $("select").change(function () {
            $('#isDirty').val(true);
        });
        $("textarea").change(function () {
            $('#isDirty').val(true);
        });
    });
</script>

MRSArchisWFApp/Views/Shared/_GridHelpers.cshtml
@using MRSArchisWFApp.Helpers

<!-- Javascript: general field helpers (partial view: _EditHelpers.cshtml) -->
<script type="text/javascript">
    function enableGridEdit() {
        $("td > input, th > input").attr("disabled", "disabled").attr("readonly", "readonly");
        $("td > select").attr("disabled", "disabled").attr("readonly", "readonly");

        var unprotectFields = $("*[class~='@SessionHandler.CurrentStep'][class~='editor-field'] > input");
        if (unprotectFields)
        {
            $(unprotectFields).removeAttr("disabled").removeAttr("readonly");
            //$(unprotectFields).filter("*[type='text'], *[type='checkbox'], *[type='radio']").parent().css("background-color", "InfoBackground");
        }

        unprotectFields = $("*[class~='@SessionHandler.CurrentStep'][class~='editor-field'] > select");
        if (unprotectFields)
        {
            $(unprotectFields).removeAttr("disabled").removeAttr("readonly");
            //$(unprotectFields).parent().css("background-color", "InfoBackground");
        }
    }

    function enableGridEditRijkshuisstijl() {
        $("li > input, th > input").attr("disabled", "disabled").attr("readonly", "readonly");
        $("li > select").attr("disabled", "disabled").attr("readonly", "readonly");        

        var unprotectFields = $("input[class~='@SessionHandler.CurrentStep'][class~='editor-field']");
        if (unprotectFields) {
            $(unprotectFields).removeAttr("disabled").removeAttr("readonly");
            $(unprotectFields).prev("label[class!='empty']").append(" *");
            //$(unprotectFields).filter("*[type='text'], *[type='checkbox'], *[type='radio']").parent().css("background-color", "InfoBackground");
        }

        unprotectFields = $("select[class~='@SessionHandler.CurrentStep'][class~='editor-field']");
        if (unprotectFields) {
            $(unprotectFields).removeAttr("disabled").removeAttr("readonly");
            $(unprotectFields).prev("label[class!='empty']").append(" *");
            //$(unprotectFields).parent().css("background-color", "InfoBackground");
        }
    }
</script>

MRSArchisWFApp/Views/Shared/_Layout.cshtml
@using MRSArchisWFApp.Helpers;
@using MRSArchisWFApp.Helpers.EPS;
@if (false)
{ <script src="../../Scripts/jquery-1.9.1-vsdoc.js" type="text/javascript"></script> }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=9" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/rijkshuisstijl/Screen.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.form.js")" type="text/javascript"></script>
    <script type="text/javascript">
        // ***************************************************************************************//
        // The Post function gets called by EPS after modifying PostanGo.js in the following way: //
        // - Locate the following line at the top                                                 //
        //    if(myFormframe != null && myFormframe.name == "formframe")                          //
        //    {                                                                                   //
        //    ...                                                                                 //
        //    }                                                                                   //
        // - Add this patch for calling the similar named function below:                         //
        //        if (myFormframe.Post) {                                                         //
        //            myFormframe.Post(Func);                                                     //
        //            return;                                                                     //
        //        }                                                                               //
        //****************************************************************************************//
        function Post(Func) {
            // Update the cache first
            UpdateCache();

            $.ajax({ url: '@Url.Content("~/Home/PWAction?Func=")' + Func, datatype: 'json', cache: false })
			    .done(function (data) {
			        if (!data.isValid) {
			            // Highlight the active tab
			            $("#menu a:contains('" + data.title + "')").each(function () {
			                if ($(this).text() == data.title) {
			                    $(this).css("color", "#ff0000");
			                    $(this).scrollTop();
			                }
			            });
			            alert(data.message);
			            return false;
			        }
			        else if (Func == "Sendup" || Func == "Close") {
			            parent.window.location.href = "/pw/client/flowlist.aspx";
			        }
			        else if (Func == "Save") {
			            alert("Gegevens zijn opgeslagen");
			        }
			    });
        }

        function UpdateCache() {
            if ($("form") && $("form").length > 0 && "@SessionHandler.IsReadonly" != "true") {
                $.ajax({ url: '@Url.Content("~/Home/UpdateCache?")' + $("form").formSerialize(), datatype: 'text', cache: false, async: false })
			    .done(function (txt) {
			        $("#updateresult").show();
			        $("#updateresult").fadeOut(1000);
			    });
            }
        }
    </script>
    <!-- Render page scripts before master disabling, posting scripts-->
    @RenderSection("PageScripts", false)


    <!-- Disable, post and active tab highligthing -->
    <script type="text/javascript">

        $(document).ready(function () {
            // Parameters in home/index method stored in session vars
            if ("@SessionHandler.CurrentStep" != "")
                $(".@SessionHandler.CurrentStep").css("display", "inline");
            if ("@SessionHandler.IsReadonly" == "true") {
                $('input, select', 'form').attr('disabled', 'disabled').attr('readonly', 'readonly');
                $('#main a').attr('href', '#').removeAttr('target');
                $('#main a').click(function () {
                    alert("Accepteer de taak om de link actief te maken");
                    return false;
                });
            }

            // Save the form when the users clicks on a link
            if ($("form") && $("form").length > 0 && "@SessionHandler.IsReadonly" != "true") {
                $("a[href!='#']").click(function () {
                    UpdateCache();
                });
            }

            // Highlight the active tab
            $("#menu a:contains('@ViewBag.Title')").each(function () {
                if ($(this).text() == "@ViewBag.Title")
                    //$(this).css("background-color", "#a6e2a6");
                    $(this).addClass("selected");
            });

            // Hide test buttons
            if (top.document.forms.length == 0 || top.document.forms[0].name != "aspnetForm")
                $("#pwbuttons").show();
        });
    </script>
</head>
<body>
    <div class="container page azure">
        <header class="header">
            <nav class="nav_bar">
                <ul id="menu" class="nav_main">
                    <li class="initiator_ZR_nz">@Html.ActionLink("Registratie", "CreateNewCase", "Case")</li>
                    <li class="user_MI_in">@Html.ActionLink("Intake", "IntakeMRSCase", "Case")</li>
                    <li class="user_AM_in">@Html.ActionLink("Intake", "IntakeAddMonument", "Case")</li>
                    <li class="user_AM_in">@Html.ActionLink("Checklijst", "Edit", "CheckList")</li>
                    <li class="user_AM_in">@Html.ActionLink("Upload dico", "Index", "Dico")</li>
                    <li class="user_AM_in">@Html.ActionLink("WGP Viewer", "ShowWGPViewer", "Dico")</li>
                    <li class="user_CM_in">@Html.ActionLink("Intake", "IntakeChangeMonument", "Case")</li>
                    <li class="user_VM_in">@Html.ActionLink("Intake", "IntakeDeleteMonument", "Case")</li>
                    <li class="initiator_ZR_nz user_MI_in user_AM_in user_CM_in user_WM_in">@Html.ActionLink("Documenten", "Index", "Document")</li>
                    <li class="initiator_ZR_nz user_MI_in user_AM_in user_CM_in user_WM_in">@Html.ActionLink("Bevindingen", "Index", "Findings")</li>
                    <li style="display: inline;">@Html.ActionLink("Zaak", "Overview", "Case")</li>
                                        
                    
                </ul>
            </nav>
        </header>

        <div class="content_wrapper1">
            <!-- Schaduw rechts -->
            <div class="content_wrapper2">
                <!-- Lichtere balk onder het menu -->
                <section id="main">
                    @RenderBody()
                </section>
            </div>
        </div>
    <footer class="footer">
        <div id="updateresult" style="border: 1px solid darkgrey; background-color: #ffeeee; margin: auto; width: 70%; padding: 4px; display: none">
            Gegevens opgeslagen, bezig met ophalen nieuwe pagina...
        </div>
        <br />
        <div class="ref">
            <img src="@Url.Content("~/Content/rijkshuisstijl/logos/RO_Footer_Homepage.png")" alt="" height="25" title="@MRSArchisWFApp.MvcApplication.About" /></div>
        @*@Html.ActionLink(MRSArchisWFApp.MvcApplication.About, "ReleaseNotes", "Home", null, new { target = "_blank", style = "text-decoration:none" })*@
        <div id="pwbuttons" style="float: right; margin-right: 10px; display: none;">
            <button onclick="Post('Save');">
                Save</button>
            |
                <button onclick="Post('SendupTest');">
                    Forward</button>
        </div>
    </footer>
    </div>
</body>
</html>